json.id @club.id
json.name @club.name
json.logo_url @club.logo_url
json.zip_code @club.zip_code
json.address @club.address
json.country @club.country
json.description @club.description
json.city @club.city
json.date_of_creation @club.date_of_creation
json.league @club.league
json.conference @club.conference
json.pool @club.pool
json.games @games
json.practices @practices
json.players @players
